#!/bin/bash

# Colors...
CK="\033[30;1m"; CR="\033[31;1m"; CG="\033[32;1m"; CY="\033[33;1m"; CB="\033[34;1m";
CM="\033[35;1m"; CC="\033[36;1m"; CW="\033[37;1m"; CE="\033[0m"   ; LF="\n";

ECHO=$(env which echo)

if [ -z "${WDIR}" ]
then
    WDIR="/opt/hachdev/buildsystem/r1701-var-dart-6ul"
fi

BUILDDIR="${WDIR}/build"
FIRST_TIME=0
cd ${WDIR}/sources/poky
if [ ! -f ${BUILDDIR}/conf/local.conf ]; then
    FIRST_TIME=1
fi

. ./oe-init-build-env ${BUILDDIR} >/dev/null

echo -e "${LF}"
echo -e " +--------------------------------------------------------------------------------------------------------+"
echo -e " |                                                                                                        |"
echo -e " |    HACH provides the following Open Source Compliant image for '${CY}HQ-Series Portable Meter${CE}' platform.    |"
echo -e " |                                                                                                        |"
echo -e " |        Image : ${CY}hqseries-portable-image${CE}                                                                 |"
echo -e " |        Kernel: ${CY}virtual/kernel${CE}                                                                          |"
echo -e " |        U-Boot: ${CY}virtual/u-boot${CE}                                                                          |"
echo -e " |                                                                                                        |"
echo -e " |    Image        - ${CY}bitbake hqseries-portable-image${CE}                                                      |"
echo -e " |    Kernel       - ${CY}bitbake virtual/kernel${CE}, ${CY}bitbake -c devshell virtual/kernel${CE}                           |"
echo -e " |    U-Boot       - ${CY}bitbake virtual/boot${CE}                                                                 |"
echo -e " |    Show Layers  - ${CY}bitbake-layers show-layers${CE}                                                           |"
echo -e " |                                                                                                        |"
echo -e " +--------------------------------------------------------------------------------------------------------+"
echo -e "${LF}"

if [ $FIRST_TIME -eq 1 ]; then
    mkdir -p conf
    cp ../sources/meta-r1701-public/buildconf/*.conf conf/
    echo -e " +------------------------------------------------------------------------+"
    echo -e " | HQ-Series Portable Meter's ${CY}Public Layer${CE} set as primary layer - ${CG}ENABLED${CE} |"
    echo -e " +------------------------------------------------------------------------+"
    echo -e "${LF}"
fi
