#!/bin/sh
### BEGIN INIT INFO
# Provides:          sendsigs
# Required-Start:
# Required-Stop:     umountnfs
# Default-Start:
# Default-Stop:      0 6
# Short-Description: Kill all remaining processes.
# Description:
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin

# Kill all processes.
echo "Sending all processes the TERM signal..."
killall5 -15
# Do we need to wait for 5 seconds? OR we can just kill all. Since gracefull shutdown of all out r1701 process has been
# done and we shoud not wait for 5 seconds for power off. Disabling below 5 seconds for now.
#sleep 5
echo "Sending all processes the KILL signal..."
killall5 -9

: exit 0
