#!/bin/sh
#logger -t acpid  "Sending Shutdown event on localhost:5555 ..."
#echo "shutdown" | /opt/hach/bin/zmq-push.sh localhost 5555
#sleep 3
#logger -t "ZMQ: Sent Shutdown event."
#exec /sbin/poweroff
