#!/bin/sh
#===============================================================================
#
#  usb-post-down
#
#  Copyright (C) 2017 by Digi International Inc.
#  All rights reserved.
#
#  This program is free software; you can redistribute it and/or modify it
#  under the terms of the GNU General Public License version 2 as published by
#  the Free Software Foundation.
#
#
#  !Description: Unload g_ether network gadget driver
#
#===============================================================================

[ "${IFACE}" != "usb0" ] && exit 0

# If g_ether module is loaded, unload it
grep -qws 'g_ether' /proc/modules && rmmod g_ether

